source 'https://rubygems.org'

gem 'rails', '5.2.6.2'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0.5'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails', '>= 4.0.1'
gem 'ember-rails', '>= 0.14.1'
gem 'ember-source'
gem 'jwt'
gem 'bcrypt-ruby'